version: '3.4'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: bridge
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./build:/root/build
    ports:
     - 80:80
