export const SET_FOLDER_DATA = 'FILESYSTEM_ACTION::SET_FOLDER_DATA';
export const GET_FOLDER_DATA = 'FILESYSTEM_ACTION::GET_FOLDER_DATA';
export const UPDATE_FOLDER_DATA = 'FILESYSTEM_ACTION::UPDATE_FOLDER_DATA';
export const SEARCH_FOLDER_FILE = 'FILESYSTEM_ACTION::SEARCH_FOLDER_FILE';
export const DOWNLOAD_FILE = 'FILESYSTEM_ACTION::DOWNLOAD_FILE';
export const GET_VERSIONS = 'FILESYSTEM_ACTION::GET_VERSIONS';
export const CLEAN_STORAGE = 'FILESYSTEM_ACTION::CLEAN_STORAGE';
export const GET_FOLDERS_TREE = 'FILESYSTEM_ACTION::GET_FOLDERS_TREE';
