export const CREATE_VOTING = 'VOTING_ACTION::CREATE_VOTING';
export const SET_VOTING_DATA = 'VOTING_ACTION::SET_VOTING_DATA';
export const UPDATE_VOTING_DATA = 'VOTING_ACTION::UPDATE_VOTING_DATA';
export const GET_VOTING_DATA = 'VOTING_ACTION::GET_VOTING_DATA';